### ISSUE TITLE
create offer

### ISSUE THREAD

**Issue by AhmedAl-Almi** [FACG6/city-in-the-south#27]
contains: 
- input title
- input position
- input description
- Use AutoCompleteTags from common components for skills and offer_type
---
### Note :100: 
 we should store the skills in an array and for the offer_type the same 
so we when sending a request for the back-end #44

**Comment by Fatmasiam** [comment]
view : #106

```javascript 
 <AutoCompleteTags
        type="offer_type"
        placeholder="eg:  fixed price
        onchange={this.handleOfferTypes}
       allowNew
       />
```
add  just ```allowNew```  props to ` AutoCompleteTags` Component
