### ISSUE TITLE
I'm using google-charts but not converted coding in swift, so please help me html coding load to web view in swift

### ISSUE THREAD

**Issue by denish09** [FACG6/city-in-the-south#70]
URL: https://developers.google.com/chart/interactive/docs/gallery/piechart#top_of_page

Coding:

<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Work',     11],
          ['Eat',      2],
          ['Commute',  2],
          ['Watch TV', 2],
          ['Sleep',    7]
        ]);

        var options = {
          title: 'My Daily Activities'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="piechart" style="width: 900px; height: 500px;"></div>
  </body>
</html>
![piechar](https://user-images.githubusercontent.com/51110192/58527981-82522100-81f2-11e9-9fc3-dc9e9bc0e29b.png)

**Comment by ashatat** [comment]
we don't work with swift or any native application
sorry @denish09
