### ISSUE TITLE
General Notes :

### ISSUE THREAD

**Issue by Fatmasiam** [FACG6/city-in-the-south#80]
1. Font-size in small screens 
2. In offer card, I think it is more powerful if you add on hover too-tips on save icon.
3. Home page skills is too large!!.
4. Home page, search is not implemented.
5.Home page, I guess member info should not presented as card.
6. Home page: result number should be changed as long as search result change

 ------ 

on  `create new offer` page

  1- we need 2 objects on the state for skills

   - one  `skills` to get all skills  `GET /api/v1/skills`  in the `componentDidMount ` function
   - the other  ` newSkills ` to get all skills from user inputs to send it to the backend
     * and the same thing for ```offer_type```

**Comment by AymanAlqoqa** [comment]
General Notes on Front-end:
- In offer card, I think it is more powerful if you add  on hover too-tips on save icon.

**Comment by Fatmasiam** [comment]
Remove All `Async` code  in  `componentWillUnMount`
