### ISSUE TITLE
General Notes : 

### ISSUE THREAD

**Issue by Fatmasiam** [FACG6/city-in-the-south#81]
Errors Code : 
1. validation errors (400) => bad request from the client 
2. un authorization (403) 
3. internal server erro (500)
4. error should be like this `{
  code:500,
  msg: 'internal server error',
}`
5. after authentication is ready we should always check that the member_id equals the authenticated member_id when requesting or posting stuff related to the logged in user [check](https://github.com/FACG6/city-in-the-south/pull/97#discussion_r292035608)

**Comment by AymanAlqoqa** [comment]
@Fatmasiam @Angham116 @alaabadra @AhmedAl-Almi @ashatat @AymanAlqoqa
